-- ==========================================
-- LUME DATABASE SETUP SCRIPT
-- Run this in the Supabase SQL Editor to set up all tables.
-- ==========================================

-- 1. Enable UUID extension
create extension if not exists "uuid-ossp";

-- ==========================================
-- 2. PROFILES TABLE
-- Stores user profile data (linked to auth.users)
-- ==========================================
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  business_name text,
  avatar_url text,
  settings jsonb default '{}'::jsonb, -- This is where Twilio config lives!
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.profiles enable row level security;

-- Policies
drop policy if exists "Users can view own profile" on public.profiles;
create policy "Users can view own profile" on public.profiles
  for select using (auth.uid() = id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile" on public.profiles
  for update using (auth.uid() = id);

drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile" on public.profiles
  for insert with check (auth.uid() = id);

-- Trigger to create profile on signup
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, business_name)
  values (
    new.id, 
    new.email, 
    new.raw_user_meta_data->>'full_name',
    'My Med Spa'
  )
  on conflict (id) do nothing; -- Prevent errors if re-running
  return new;
end;
$$ language plpgsql security definer;

-- Drop trigger if exists to avoid error on recreation
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- ==========================================
-- 3. CLIENTS TABLE
-- Stores client data linked to specific users
-- ==========================================
create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  
  -- Personal Info
  first_name text,
  last_name text,
  email text,
  phone text,
  
  -- Business Data
  status text default 'active',
  membership_type text default 'none',
  total_spend numeric default 0,
  visit_count integer default 0,
  
  -- Dates
  join_date timestamp with time zone default now(),
  last_visit timestamp with time zone,
  expire_date timestamp with time zone,
  birthday date,
  
  -- Sessions
  total_sessions integer default 0,
  remaining_sessions integer default 0,
  
  -- AI Analysis (Cached)
  health_score integer default 50,
  churn_risk integer default 0,
  recommendation text,
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.clients enable row level security;

-- Policies
drop policy if exists "Users can view own clients" on public.clients;
create policy "Users can view own clients" on public.clients
  for select using (auth.uid() = user_id);

drop policy if exists "Users can insert own clients" on public.clients;
create policy "Users can insert own clients" on public.clients
  for insert with check (auth.uid() = user_id);

drop policy if exists "Users can update own clients" on public.clients;
create policy "Users can update own clients" on public.clients
  for update using (auth.uid() = user_id);

drop policy if exists "Users can delete own clients" on public.clients;
create policy "Users can delete own clients" on public.clients
  for delete using (auth.uid() = user_id);

-- Create index for performance
create index if not exists clients_user_id_idx on public.clients (user_id);


-- ==========================================
-- 4. COMMUNICATIONS TABLE
-- Stores all messages (SMS, Email, Notes) linked to clients
-- ==========================================

create table if not exists public.communications (
  id bigint generated by default as identity primary key,
  client_id bigint references public.clients(id) on delete cascade not null,
  user_id uuid references auth.users not null,
  type text not null, -- 'sms', 'email', 'note', 'nudge'
  direction text not null, -- 'inbound', 'outbound'
  content text,
  status text default 'sent', -- 'sent', 'received', 'delivered', 'failed'
  sid text, -- Twilio Message SID or Email ID
  metadata jsonb default '{}'::jsonb,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.communications enable row level security;

-- Policies
drop policy if exists "Users can view own communications" on public.communications;
create policy "Users can view own communications" on public.communications
  for select using (auth.uid() = user_id);

drop policy if exists "Users can insert own communications" on public.communications;
create policy "Users can insert own communications" on public.communications
  for insert with check (auth.uid() = user_id);

drop policy if exists "Users can update own communications" on public.communications;
create policy "Users can update own communications" on public.communications
  for update using (auth.uid() = user_id);

drop policy if exists "Users can delete own communications" on public.communications;
create policy "Users can delete own communications" on public.communications
  for delete using (auth.uid() = user_id);

-- Realtime
-- Note: 'supabase_realtime' publication usually exists, but might error if not.
-- We wrap in a do block or just assume standard setup.
alter publication supabase_realtime add table public.communications;
