-- COMMUNICATIONS TABLE
-- Stores all messages (SMS, Email, Notes) linked to clients

create table public.communications (
  id bigint generated by default as identity primary key,
  client_id bigint references public.clients(id) on delete cascade not null,
  user_id uuid references auth.users not null, -- Owner of the client
  type text not null, -- 'sms', 'email', 'note', 'nudge'
  direction text not null, -- 'inbound', 'outbound'
  content text,
  status text default 'sent', -- 'sent', 'received', 'delivered', 'failed'
  sid text, -- Twilio Message SID or Email ID
  metadata jsonb default '{}'::jsonb,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.communications enable row level security;

-- Policies: Users see ONLY their own client communications
create policy "Users can view own communications" on public.communications
  for select using (auth.uid() = user_id);

create policy "Users can insert own communications" on public.communications
  for insert with check (auth.uid() = user_id);

create policy "Users can update own communications" on public.communications
  for update using (auth.uid() = user_id);

create policy "Users can delete own communications" on public.communications
  for delete using (auth.uid() = user_id);

-- Realtime
alter publication supabase_realtime add table public.communications;
